# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
    ]
